name: verifiable-expressions
version: '0.6.2'
category: Language
author: Bradley Hardy
maintainer: madgenhetic@gmail.com
github: camfort/verifiable-expressions
license: Apache-2.0
synopsis: An intermediate language for Hoare logic style verification.
description:
  A typed intermediate language for Hoare logic style verification. It defines
  the intermediate language and combinators to interact it.

extra-source-files:
- CHANGELOG.md

dependencies:
- base >=4.9 && <5
- containers >=0.5.7 && <0.7
- transformers >=0.5 && <0.7
- mtl >=2.0 && <3
- lens >=4.16.1 && <5.5
- union >=0.1.2 && <0.2
- vinyl >=0.14.3 && <0.15

when:
- condition: impl(ghc >= 9.6)
  dependencies:
  - sbv >=10.0 && <11
- condition: impl(ghc < 9.6)
  dependencies:
  - sbv >=8.0 && <10

library:
  ghc-options: -Wall
  exposed-modules:
  - Language.Expression
  - Language.Expression.Example
  - Language.Expression.Choice
  - Language.Expression.Scope
  - Language.Expression.GeneralOp
  - Language.Expression.Prop
  - Language.Expression.Pretty
  - Language.Expression.Util
  - Language.Verification
  - Language.Verification.Conditions
  - Language.Verification.Core
  - Language.While.Hoare
  - Language.While.Hoare.Prover
  - Language.While.Syntax
  - Language.While.Syntax.Sugar
  - Language.While.Test
