name: verifiable-expressions
version: '0.5.0'
category: Language
author: Bradley Hardy
maintainer: madgenhetic@gmail.com
github: camfort/verifiable-expressions
license: Apache-2.0
synopsis: An intermediate language for Hoare logic style verification.
description:
  A typed intermediate language for Hoare logic style verification. It defines
  the intermediate language and combinators to interact it.
dependencies:
- base >=4.9 && <5
- containers >=0.5.7 && <=0.6.0.1
- transformers >=0.5 && <0.6
- mtl >=2.0 && <3
- lens >=4.16.1 && <5
- sbv >=7.0 && <8
- union >=0.1.1 && <0.2
- vinyl >=0.8.1 && <0.9
library:
  ghc-options: -Wall
  exposed-modules:
  - Language.Expression
  - Language.Expression.Example
  - Language.Expression.Choice
  - Language.Expression.Scope
  - Language.Expression.GeneralOp
  - Language.Expression.Prop
  - Language.Expression.Pretty
  - Language.Expression.Util
  - Language.Verification
  - Language.Verification.Conditions
  - Language.Verification.Core
  - Language.While.Hoare
  - Language.While.Hoare.Prover
  - Language.While.Syntax
  - Language.While.Syntax.Sugar
  - Language.While.Test
