name: verifiable-expressions
version: '0.3.0.0'
category: Language
author: Bradley Hardy
maintainer: bch29@cam.ac.uk
license: Apache-2.0
dependencies:
- base >=4.9 && <4.11
- containers >=0.5.7 && <0.6
- transformers >=0.5 && <0.6
- mtl >=2.0 && <3
- lens >=4.10 && <5
- sbv >=7.0 && <8
- union >=0.1.1 && <0.2
- vinyl >=0.6 && <0.7
- distributive >= 0.5 && <0.6
library:
  ghc-options: -Wall
  exposed-modules:
  - Language.Expression
  - Language.Expression.Example
  - Language.Expression.Choice
  - Language.Expression.Scope
  - Language.Expression.GeneralOp
  - Language.Expression.Prop
  - Language.Expression.Pretty
  - Language.Expression.Util
  - Language.Verification
  - Language.Verification.Conditions
  - Language.Verification.Core
  - Language.While.Hoare
  - Language.While.Hoare.Prover
  - Language.While.Syntax
  - Language.While.Syntax.Sugar
  - Language.While.Test
  - Data.Vinyl.Curry
